### ISSUE TITLE
debug CSOSA

### ISSUE THREAD

**Issue by rochelle-snyder** [judgelord/correspondence#48]
also edit merge file to pull it in

**Comment by Maggie-Nead** [comment]
created ID, chamber and agency column
formatted date
string split to separate members
extracted member names


Script runs through the merge file without error but the majority of members in the dataset are not matching. This might be because; there are a lot of NA dates, most members only have last names, or because there is no way to pull chamber information from data set.

**Comment by Maggie-Nead** [comment]
Added first names to dataset 

To Do: 
Check that first names are not errors
Remove blank observations

**Comment by Maggie-Nead** [comment]
Made "LetterID" and "ID" #80 
Fixed some NA dates
Code runs through merge file without error. 84 names are not matched after merge most are blank spaces or not members, some are not matching because they don't have a chamber/date/first-name.

**Comment by judgelord** [comment]
@fsabirinali, A few observations are failing to correctly format DATE: 
"chaffetz" x 1: DATE = NA
"meadows" x 1: DATE = NA
"shuster" x 1: DATE = NA

**Comment by Maggie-Nead** [comment]
@judgelord Dates look good, switched from added first and last names to match on chamber after chamber was pasted into FROM column. All but 9 are matched in merge and these are strings created from the string split.

**Comment by Maggie-Nead** [comment]
Fixed some dates in the google doc and fixed typo for Senator Coons. All observations are matched except for 9 non-observations.
