### ISSUE TITLE
clean script for TVA

### ISSUE THREAD

**Issue by rochelle-snyder** [judgelord/correspondence#50]

**Comment by Maggie-Nead** [comment]
Started Script
Coded for agency and a string split to separate multiple members
Ran extract member names

To Do:
Date format does not work

**Comment by Maggie-Nead** [comment]
Script for TVA looks good and runs through the merge without error. 45 out of 121 are not matching, a few are state legislators he others are not matching after merge because they only have last names and no chamber. #62

**Comment by Maggie-Nead** [comment]
Made "LetterID" and "ID"
Added first names for those without chamber
Extracted 2 names from SUBJECT
Coded notes for Duncan and Markey that have multiple members with the same last name and doesn't match

34 out of 123 are not matching in the merge file, most are state legislators. Duncan and Markey do not match because multiple members have the same last name.
Joe Pitts should match in the merge file but does not #62

**Comment by Maggie-Nead** [comment]
Made "LetterID" and "ID"
Added first names for those without chamber
Extracted 2 names from SUBJECT
Coded notes for Duncan and Markey that have multiple members with the same last name and doesn't match

34 out of 123 are not matching in the merge file, most are state legislators. Duncan and Markey do not match because multiple members have the same last name.
Joe Pitts should match in the merge file but does not #62

**Comment by Maggie-Nead** [comment]
Duncan and Markey both do not have first names and do not have chambers 
Duncan has 17 letters (Letter ID's 6, 4, 11, 13, 14, 16, 20, 22, 26, 27, 63, 72, 74, 76, 86, 95, 110)
Markey has 2 letters (LetterID's 96 & 103)
